server:
  port: 8180
spring: 
  redis:
    database: 8
    host: 115.29.78.228
    port: 7000
    password: clianmeng.com
    max-active: 20
    max-wait: 120000
    max-idle: 20
    min-idle: 2
    timeout: 0
  thymeleaf: 
    cache: true
logging:
  config: classpath:logback.xml
  path: /logs/njwd
  level: INFO
dubbo: 
   registryAddress: zookeeper://192.168.31.151:2181
   registryCheck: false
   registryTimeout: 5000
   applicationName: njwd-dubbo-monitor
   annotationPackage: com.njwd.rpc.monitor.core.dubbo
   protocolName: dubbo
   protocolPort: 20881
sweager : 
  enable: true
