spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization-inclusion: non_null
  http:
    multipart:
      enabled: true
      max-file-size: 10Mb
  aop: 
    proxy-target-class: true
  thymeleaf: 
    prefix: classpath:/th/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    content-type: text/html
    cache: false
server:
  context-path: /monitor
dubbo: 
   registryAddress: zookeeper://192.168.31.243:2181
   registryCheck: false
   registryTimeout: 5000
   applicationName: njwd-dubbo-monitor
   annotationPackage: com.njwd.rpc.monitor.core.dubbo
   protocolName: dubbo
   protocolPort: 20881
sweager : 
  enable: false